apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-argocd
  labels:
    app: ci-cd-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-argocd
  template:
    metadata:
      labels:
        app: ci-cd-argocd
    spec:
      containers:
        - name: ci-cd-argocd
          image: jainishparmar/ci_cd_argocd:78181c6adc7745c5b0574b62c0c0ac6f6d8f57b8
          ports:
            - containerPort: 8080
