apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-argocd
  labels:
    app: ci-cd-argocd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ci-cd-argocd
  template:
    metadata:
      labels:
        app: ci-cd-argocd
    spec:
      containers:
        - name: ci-cd-argocd
          image: jainishparmar/ci_cd_argocd:77108c50b87d41d30cc6d44549362036879b851d
          ports:
            - containerPort: 8080
