apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-argocd
  labels:
    app: ci-cd-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-argocd
  template:
    metadata:
      labels:
        app: ci-cd-argocd
    spec:
      containers:
        - name: ci-cd-argocd
          image: jainishparmar/ci_cd_argocd:57e30ad16d09ba9b880dfea2336d86291e9e1581
          ports:
            - containerPort: 8080
